"""
AppraisAI — Admin / Testing Router
=====================================
POST /admin/test-order  — Create a demo order with custom property details
                          and trigger AI generation without Stripe payment.
                          Owner use only.
"""
import os
import logging
from typing import Optional
from fastapi import APIRouter, BackgroundTasks, HTTPException, Header
from pydantic import BaseModel
from supabase import create_client
from routers.orders import run_ai_generation

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/admin", tags=["admin"])

def get_db():
    return create_client(
        os.getenv("SUPABASE_URL"),
        os.getenv("SUPABASE_SERVICE_ROLE_KEY")
    )

def verify_admin(x_admin_key: str = Header(None)):
    """Simple API key check — set ADMIN_SECRET in Railway env vars."""
    secret = os.getenv("ADMIN_SECRET", "appraisai-test-2024")
    if x_admin_key != secret:
        raise HTTPException(status_code=401, detail="Invalid admin key")

class DemoOrderBody(BaseModel):
    property_address:  Optional[str] = "123 Main Street"
    city_state_zip:    Optional[str] = "Pittsburgh, PA 15222"
    property_type:     Optional[str] = "Office"
    estimated_value:   Optional[str] = "$2,500,000"
    gba:               Optional[str] = "10,000 SF"
    year_built:        Optional[str] = "1998"
    purpose:           Optional[str] = "mortgage underwriting and internal decision-making"
    additional_notes:  Optional[str] = ""
    service_level:     Optional[str] = "professional"
    client_name:       Optional[str] = "Demo Client"
    client_email:      Optional[str] = "owner@apprais-ai.com"

def get_demo_appraiser_id(db):
    """Look up the appraiser by email so we always get the right user."""
    res = db.table("users").select("id").eq("email", "appraiser@apprais-ai.com").limit(1).execute()
    return res.data[0]["id"] if res.data else None

@router.post("/test-order")
async def create_test_order(
    background_tasks: BackgroundTasks,
    body: DemoOrderBody = None,
    x_admin_key: str = Header(None),
):
    verify_admin(x_admin_key)
    if body is None:
        body = DemoOrderBody()
    db = get_db()
    user_res = db.table("users").upsert(
        {"email": body.client_email, "full_name": body.client_name,
         "company": "AppraisAI Demo", "role": "client"},
        on_conflict="email"
    ).execute()
    client_id = user_res.data[0]["id"]
    assigned_appraiser_id = get_demo_appraiser_id(db)
    order_number = db.rpc("generate_order_number").execute().data
    order_res = db.table("orders").insert({
        "order_number": order_number, "client_id": client_id,
        "assigned_appraiser_id": assigned_appraiser_id,
        "property_address": body.property_address, "city_state_zip": body.city_state_zip,
        "property_type": body.property_type, "estimated_value": body.estimated_value,
        "gba": body.gba, "year_built": body.year_built, "purpose": body.purpose,
        "additional_notes": body.additional_notes or "DEMO ORDER — generated by owner",
        "service_level": body.service_level, "price_cents": 220000,
        "status": "paid", "stripe_payment_status": "owner_demo",
    }).execute()
    order = order_res.data[0]
    order_id = order["id"]
    db.table("order_events").insert({
        "order_id": order_id, "event_type": "order_created",
        "description": f"DEMO order {order_number} created by owner (no payment)"
    }).execute()
    background_tasks.add_task(run_ai_generation, order_id, order)
    return {"message": "Demo order created.", "order_id": order_id,
            "order_number": order_number, "status": "ai_processing"}

@router.get("/orders")
async def list_all_orders(x_admin_key: str = Header(None)):
    verify_admin(x_admin_key)
    db = get_db()
    orders = db.table("orders").select(
        "id, order_number, property_address, status, service_level, assigned_appraiser_id, created_at"
    ).order("created_at", desc=True).limit(50).execute()
    return {"orders": orders.data}

@router.post("/assign-all-orders")
async def assign_all_orders(x_admin_key: str = Header(None)):
    """Assign ALL orders (including already-assigned ones) to the demo appraiser."""
    verify_admin(x_admin_key)
    db = get_db()
    appraiser_id = get_demo_appraiser_id(db)
    if not appraiser_id:
        raise HTTPException(404, "Appraiser appraiser@apprais-ai.com not found")
    result = db.table("orders").update({"assigned_appraiser_id": appraiser_id})         .neq("id", "00000000-0000-0000-0000-000000000000").execute()
    updated_count = len(result.data) if result.data else 0
    return {"message": f"Assigned {updated_count} orders to appraiser",
            "appraiser_id": appraiser_id, "updated_count": updated_count}
