"""
AppraisAI — Admin / Testing Router
=====================================
POST /admin/test-order  — Create a test order and trigger AI generation
                          without Stripe payment. Owner use only.
"""

import os
import logging
from fastapi import APIRouter, BackgroundTasks, HTTPException, Header
from supabase import create_client
from routers.orders import run_ai_generation

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/admin", tags=["admin"])


def get_db():
    return create_client(
        os.getenv("SUPABASE_URL"),
        os.getenv("SUPABASE_SERVICE_ROLE_KEY")
    )


def verify_admin(x_admin_key: str = Header(None)):
    """Simple API key check — set ADMIN_SECRET in Railway env vars."""
    secret = os.getenv("ADMIN_SECRET", "appraisai-test-2024")
    if x_admin_key != secret:
        raise HTTPException(status_code=401, detail="Invalid admin key")


# ── POST /admin/test-order ────────────────────────────────────────────────────
@router.post("/test-order")
async def create_test_order(background_tasks: BackgroundTasks,
                             x_admin_key: str = Header(None)):
    """
    Creates a test appraisal order marked as 'paid' and immediately kicks
    off AI generation — no Stripe payment required. For owner testing only.
    """
    verify_admin(x_admin_key)
    db = get_db()

    # 1. Upsert a test user
    user_res = db.table("users").upsert(
        {
            "email": "owner@apprais-ai.com",
            "full_name": "Test Owner",
            "company": "AppraisAI",
            "role": "client",
        },
        on_conflict="email"
    ).execute()
    client_id = user_res.data[0]["id"]

    # 2. Generate order number
    order_number = db.rpc("generate_order_number").execute().data

    # 3. Create a test order record (already paid, no Stripe)
    order_res = db.table("orders").insert({
        "order_number":     order_number,
        "client_id":        client_id,
        "property_address": "123 Main Street",
        "city_state_zip":   "Pittsburgh, PA 15222",
        "property_type":    "Office",
        "estimated_value":  "$2,500,000",
        "gba":              "10,000 SF",
        "year_built":       "1998",
        "purpose":          "mortgage underwriting and internal decision-making",
        "additional_notes": "TEST ORDER — generated by owner for QA purposes",
        "service_level":    "professional",
        "price_cents":      220000,
        "status":           "paid",
        "stripe_payment_status": "test",
    }).execute()
    order = order_res.data[0]
    order_id = order["id"]

    # 4. Log the test event
    db.table("order_events").insert({
        "order_id": order_id,
        "event_type": "order_created",
        "description": f"TEST order {order_number} created by owner (no payment)"
    }).execute()

    # 5. Fire off AI generation in background
    background_tasks.add_task(run_ai_generation, order_id, order)

    return {
        "message": "Test order created. AI generation started in background.",
        "order_id": order_id,
        "order_number": order_number,
        "status": "ai_processing",
        "note": "Check the Appraiser Portal in ~2 minutes — the draft will appear there."
    }


# ── GET /admin/orders — List all orders (for quick debugging) ─────────────────
@router.get("/orders")
async def list_all_orders(x_admin_key: str = Header(None)):
    """Returns all orders with their current status. Owner use only."""
    verify_admin(x_admin_key)
    db = get_db()
    orders = db.table("orders").select(
        "id, order_number, property_address, status, service_level, created_at"
    ).order("created_at", desc=True).limit(20).execute()
    return {"orders": orders.data}
